#!/bin/bash
version='1.1.0' # -- [main OFF/major ON/minor ON]
OPENCV_VERSION='4.5.0'

DK_PREFIX=/usr/local/dklaxz
DK_EXT_PREFIX=$DK_PREFIX/dklaxz-extra
DKTMP_PREFIX=/tmp/dklaxz
DK_REPO=https://github.com/minlaxz/ml-in-docker.git

if [ $# -eq 0 ]; then
echo -e "\e[1;31m"
    printf "[not an option] dklaxz --help    for usage.\n"
echo -e "\e[m"
else
    stVar=$1 #major
    ndVar=$2 #minor

    # make sure update with dklaxz-extra/help
    case "$stVar" in
        --help) bash -c $DK_EXT_PREFIX/help ;;
        --map) bash -c $DK_EXT_PREFIX/map ;;

        --build-cv) if [[ $ndVar == "" ]]; then
            echo "This need GPU(s)'(!s) compute capability number. eg:7.6"
            echo "more info > https://developer.nvidia.com/cuda-gpus"
            else bash $DK_EXT_PREFIX/build_opencv $ndVar
            fi
            ;;
        --help-cv) bash -c $DK_EXT_PREFIX/howto_opencv ;;

        # --build-tf) if [[ ]]

        --version) printf "version : ${version} Main/Build/Minor\n" ;;
        --update) bash $DK_EXT_PREFIX/check_dklaxz $DK_PREFIX $DKTMP_PREFIX $DK_REPO ;;
        --update-rc) bash -c $DK_EXT_PREFIX/check_rc ;; # for some weird cases
        *) printf "[not an option $stVar] dklaxz --help for usage.\n" ;;
    esac
fi