ARG UBUNTU_VERSION=18.04

ARG DK_PREFIX=/usr/local/dklaxz
ARG DK_EXT_PREFIX=${DK_PREFIX}/dklaxz-extra

FROM ubuntu:${UBUNTU_VERSION}

SHELL ["/bin/bash", "-c"]

RUN apt-get update 1>/dev/null \
&& apt-get upgrade -y 1>/dev/null \
&& apt-get install -y wget git 1>/dev/null

COPY laxz.bashrc /etc/bash.bashrc
RUN chmod a+rwx /etc/bash.bashrc

RUN mkdir -p /usr/local/dklaxz/dklaxz-extra/
COPY dklaxz /usr/local/dklaxz/dklaxz
COPY dklaxz-extra /usr/local/dklaxz/dklaxz-extra/
RUN chmod 755 /usr/local/dklaxz/dklaxz /usr/local/dklaxz/dklaxz-extra/*
RUN ln -s /usr/local/dklaxz/dklaxz /usr/bin/dklaxz

RUN mkdir -p /tf/tensorflow-tutorials && chmod -R a+rwx /tf/
COPY ./examples-ipynb.txt /tf
RUN mkdir /.local && chmod a+rwx /.local
WORKDIR /tf/tensorflow-tutorials
RUN wget -qi ../examples-ipynb.txt && apt-get autoremove -y
WORKDIR /tf